set-option -g status-position bottom
set-option -g destroy-unattached on

set-window-option -g automatic-rename on
set-window-option -g window-status-format '#{@claude_status}:#W'
set-window-option -g window-status-current-format '#{@claude_status}:#W'

bind-key n new-window -c '#{pane_current_path}' 'nu -e "claude"'
bind-key h if-shell -F '#{window_start_flag}' 'last-window' 'previous-window'
bind-key l if-shell -F '#{window_end_flag}' 'first-window' 'next-window'
