[colors]
border = "#393552" # overlay

[colors.files_list]
item_fg = "#e0def4" # text
item_active_fg = "#f6c177" # gold

[colors.diff]
navigation_fg = "#f6c177" # gold
hunk_fg = "#c4a7e7" # iris
hunk_bg = "#44415a" # highlight_med
line_added_fg = "#9ccfd8" # foam
line_deleted_fg = "#eb6f92" # love
line_unmodified_fg = "#908caa" # subtle
line_filler_bg = "#2a273f" # surface
