[logging]
enabled = true
path = "/tmp/diffv.log"

# rose-pine moon
[colors.palette]
overlay = "#393552"
surface = "#2a273f"
subtle = "#908caa"
text = "#e0def4"
gold = "#f6c177"
rose = "#ea9a97"
love = "#eb6f92"
foam = "#9ccfd8"
iris = "#c4a7e7"
highlight_med = "#44415a"

[colors]
border = "$overlay"
border_active = "$rose"

[colors.files_list]
stats_fg = "$text"
item_fg = "$text"
item_active_fg = "$gold"

[colors.diff]
stats_fg = "$text"
hunk_fg = "$iris"
hunk_bg = "$highlight_med"
line_added_fg = "$foam"
line_deleted_fg = "$love"
line_unmodified_fg = "$subtle"
line_filler_bg = "$surface"
